appName: contact-api

image:
  repository: jalgraves/contact_api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 5012

ingress:
  enabled: false

db:
  dbName: contact
  host: postgres.default.svc.cluster.local
  port: 5432

logLevel: INFO

aws_access_key_id:
aws_default_region:
aws_secret_access_key:
email_recipient:
second_email_recipient:
slack_channel:
slack_orders_channel:
slack_orders_webhook_url:
slack_partys_channel:
slack_partys_webhook_url:
slack_user:
slack_webhook_url:
support_email_address:
support_phone_number:
test_email_recipient:
